id: medcom.fhir.dk.carecommunication
canonical: http://medcomfhir.dk/ig/carecommunication
name: MedComCarecommunication
title: "DK MedCom Carecommunication"
description: The DK MedCom Carecommunication IG
status: active
version: 4.0.3
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: release
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  hl7.fhir.dk.core: 
    uri: https://hl7.dk/fhir/core/3.2.0/
    version: 3.2.0
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.messaging: 2.2.2
  medcom.fhir.dk.terminology: 1.7.0
  medcom.fhir.dk.messagedefinitions: 1.0.1-trial-use 
  
menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Examples: examples.html
  Artifacts: artifacts.html
  Downloads: downloads.html
  Dependencies: dependencies.html

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
