@startuml CareCommunication

hide empty members

class "MedComCareCommunicationMessage" as message <<MedComMessagingMessage>>
class "MedComCareCommunicationMessageHeader" as messageheader <<MedComMessagingMessageHeader>>
class "MedComMessagingProvenance" as provenance
class "MedComMessagingOrganization" as messagingOrganization <<MedComCoreOrganization>>
class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCoreEncounter" as encounter
class "Organization" as recipientOrganization 
class "MedComCorePractitionerRole" as recipientRole
class "MedComCorePractitioner" as author

message -- messageheader : "entry"
message -- provenance : "entry"
messageheader -- messagingOrganization : "sender"
messageheader -- messagingOrganization : "receiver"
messageheader -- messagingOrganization : "carbon copy"
messageheader -- communication : "focus"
communication -- encounter : "encounter"
communication -- patient : "subject"
communication -- recipientOrganization : "sender"
communication -- recipientRole : "sender"
communication -- recipientOrganization : "recipient"
communication -- recipientRole : "recipient"
communication -- author : "payload author"

encounter -patient :"subject"
@enduml