@startuml CareCommunicationMessageHeader

hide empty members

top to bottom direction

class "MedComCareCommunicationMessageHeader" as messageheader <<MedComMessagingMessageHeader>>
class "MedComMessagingOrganization" as messagingOrganization <<MedComCoreOrganization>>
class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCorePractitionerRole" as authorRole
class "Sender or recipient" as senderRec
class "MedComCorePractitioner" as author


messageheader -- communication : "focus"
communication -- patient : "subject"
communication -- authorRole : "payload author"
communication -- senderRec : "sender/recipient"
authorRole -- author : "author"


messageheader -- messagingOrganization : "receiver"
messageheader -- messagingOrganization : "sender"
@enduml