@startuml CareCommunicationMessageHeader

hide empty members

top to bottom direction

class "MedComCareCommunicationMessageHeader" as messageheader <<MedComMessagingMessageHeader>>
class "MedComMessagingOrganization" as messagingOrganization <<MedComCoreOrganization>>
class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCorePractitionerRole" as pracRole
class "MedComCoreCareTeam" as careteam
class "MedComCorePractitioner" as author
class "MedComCoreEncounter" as encounter
class "MedComCoreOrganization" as organization

messageheader -- communication : "focus"
communication -- patient : "subject"
communication -- pracRole : "author"
communication -- careteam : "sender"
communication -- careteam : "recipient"
communication -- pracRole : "sender"
communication -- pracRole : "recipient"
pracRole -- author : "practitioner"
pracRole -- organization : "organization"
careteam -- organization : "managingOrganization"
communication -- encounter : "encounter"


messageheader -- messagingOrganization : "receiver"
messageheader -- messagingOrganization : "sender"
@enduml