@startuml CareCommunication

hide empty members

top to bottom direction

class "MedComCareCommunicationMessage" as message <<MedComMessagingMessage>>
class "MedComCareCommunicationMessageHeader" as messageheader <<MedComMessagingMessageHeader>>
class "MedComMessagingProvenance" as provenance
class "MedComMessagingOrganization" as messagingOrganization <<MedComCoreOrganization>>
class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCorePractitionerRole" as authorRole
class "Sender or recipient" as senderRec
class "MedComCorePractitioner" as author


message -- messageheader : "entry"
messageheader -- communication : "focus"
communication -- patient : "subject"
communication -- authorRole : "payload author"
message -- provenance : "entry"
provenance -- messageheader : "target" 
provenance -- messagingOrganization : "agent.who"
communication -- senderRec : "sender/recipient"
authorRole -- author : "author"


messageheader -- messagingOrganization : "receiver"
messageheader -- messagingOrganization : "sender"
@enduml