/' @startuml CCNewMessageAtt

'layout
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
  }
hide circle
hide empty members
skinparam SameClassWidth true
skinparam Ranksep 10


'title
title Simplified example: New message with Attachment, Sender, Recipient and Encounter

'Message 1: New message with Attachment, Recipient and Encounter
package "CareCommunication message: New message with Attachment, Recipient and Encounter" as new <<Frame>>{
    class "Bundle (MedComCareCommunicationMessage)" as newB {
        id = "6f7e4c80-551a-11ed-bdc3-0242ac120002"
        type = "message"
        timestamp = "2023-03-01T09:00:00+01:00"
    }
    class "MessageHeader (MedComCareCommunicationMessageHeader)" as newMH{
        id = "dc04b8c2-5519-11ed-bdc3-0242ac120002"
        event.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-eventCodes"
        event.code = "care-communication-message"
        destination.use.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-destinationUse"
        destination.use.code = "primary"
        destination.endpoint = "https://sor2.sum.dsdn.dk/#id=953741000016009"
        destination.receiver.reference = "Organization/b75abdfa-5519-11ed-bdc3-0242ac120002"
        sender.reference = "Organization/c5c393ee-5519-11ed-bdc3-0242ac120002"
        source.endpoint = "https://sor2.sum.dsdn.dk/#id=265161000016000"
        focus.reference = "Communication/487e2238-527b-11ec-bf63-0242ac130002"
    }
    class "Patient (MedComCorePatient)" as newPT{
        id = "833cef33-3726-433b-855d-e566aaa65fe1"
        identifier.system = "urn:oid:1.2.208.176.1.2"
        identifier.value = "2509479989"
        name.use = "official"
        name.family = "Elmer"
        name.given[0] = "Bruno"
        name.given[1] = "Test"
    }
    class "Communication (MedComCareCommunication)" as newCom{
        id = "487e2238-527b-11ec-bf63-0242ac130002"
        status.system = "http://hl7.org/fhir/event-status" 
        status.code = "unknown"
        category.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-careCommunication-categoryCodes"
        category.code= "carecoordination"
        subject.reference = "Patient/833cef33-3726-433b-855d-e566aaa65fe1"
        recipient.reference = "CareTeam/fb1d34fe-6672-11ed-9022-0242ac120002"
        extension.sender.reference = "CareTeam/f693506a-6903-11ed-9022-0242ac120002"
        payload[0].contentString = "Regarding the rehabilitation plan, please notice that..."
        payload[0].extension:date = "2023-03-01T09:00:00+01:00"
        payload[0].extension:author.reference = "PractitionerRole/35bb99e4-551a-11ed-bdc3-0242ac120002"
        payload[0].extension:authorContact.value = "38683868"
        payload[1].contentAttachment.data = "JVBERi0xLjcNCiW1tbW1DQoxIDAgb2JqDQo8PC9U..."
        payload[1].contentAttachment.title = "Rehabilitationplan"
        payload[1].extension:date = "2023-03-01T09:00:00+01:00"
        payload[1].contentAttachment.contentType = "application/pdf"
        payload[1].contentAttachment.creation = "2023-02-25T08:00:00+01:00"
        payload[1].extension:author.reference = "PractitionerRole/35bb99e4-551a-11ed-bdc3-0242ac120002"
        payload[1].extension:authorContact.value = "38683868"
    }
    class "PractitionerRole (MedComCorePractitionerRole)" as newPracR{
        id = "35bb99e4-551a-11ed-bdc3-0242ac120002"
        practitioner.reference = "Practitioner/20eac382-551a-11ed-bdc3-0242ac120002"
        code.system = "https://medcomfhir.dk/ig/terminology/CodeSystem/medcom-core-PractitionerRolesSKSadministrativ"
        code.value = "sygeplejerske"
    }
    class "Practitioner (MedComCorePractitioner)" as newPrac{
        id = "20eac382-551a-11ed-bdc3-0242ac120002"
        name.family = "Michael"
        name.given = "Burns"
    }
    class "PractitionerRole (MedComCorePractitionerRole)" as newPracR{
        id = "27eb8ec0-1b01-4bb3-a6b3-8b05cf2d3b85"
        practitioner.reference = "Practitioner/fd8556e0-5234-4203-b61e-929eabb92605"
        code.system = "https://medcomfhir.dk/ig/terminology/CodeSystem/medcom-core-PractitionerRolesSKSadministrativ"
        code.value = "sygeplejerske"
    }
    class "Practitioner (MedComCorePractitioner)" as newPrac{
        id = "fd8556e0-5234-4203-b61e-929eabb92605"
        name.family = "Michael"
        name.given = "Burns"
    }
    class "Receiver (MedComMessagingOrganization)" as newROrg{
        id = "b75abdfa-5519-11ed-bdc3-0242ac120002"
        identifier[0].system = "https://www.gs1.org/gln"
        identifier[0].value = "5790001348120"
        identifier[1].system = "urn:oid:1.2.208.176.1.1"
        identifier[1].value = "953741000016009"
    }
    class "Sender (MedComMessagingOrganization)" as newSOrg{
        id = "c5c393ee-5519-11ed-bdc3-0242ac120002"
        identifier[0].system = "https://www.gs1.org/gln"
        identifier[0].value = "5790000209354"
        identifier[1].system = "urn:oid:1.2.208.176.1.1"
        identifier[1].value = "265161000016000"
    }
    class "Provenance (MedComMessagingProvenance)" as newPRO{
        id = "ee619a58-5519-11ed-bdc3-0242ac120002"
        target.reference = "MessageHeader/dc04b8c2-5519-11ed-bdc3-0242ac120002"
        occuredDateTime = "2023-03-01T09:00:00+01:00"
        recorded = "2023-03-01T09:00:11"
        activity.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-activityCodes"
        activity.code = "new-message"
        agent.who.reference = "Organization/c5c393ee-5519-11ed-bdc3-0242ac120002"
    }

newB -[hidden]- newMH
newMH -[hidden]-newPT
newPT-[hidden]-newCom
newCom -[hidden]-newPracR
newPracR-[hidden]-newPrac
newPrac-[hidden]--newEnc
newEnc-[hidden]-newROrg
newROrg-[hidden]-recipientCare
recipientCare-[hidden]-newSOrg
newSOrg-[hidden]-senderCare
senderCare-[hidden]-newPRO


@enduml
 '/