@startuml CareCommunicationCommunication

hide empty members

class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCorePractitionerRole" as pracRole
class "MedComCoreCareTeam" as careteam
class "MedComCorePractitioner" as author



communication -- patient : "subject"
communication -- pracRole : "author"
communication -- careteam : "sender"
communication -- careteam : "recipient"
communication -- pracRole : "sender"
communication -- pracRole : "recipient"
pracRole -- author : "practitioner"

@enduml