@startuml CareCommunication

hide empty members

top to bottom direction

class "MedComCareCommunicationMessage" as message <<MedComMessagingMessage>>
class "MedComCareCommunicationMessageHeader" as messageheader <<MedComMessagingMessageHeader>>
class "MedComMessagingProvenance" as provenance
class "MedComMessagingOrganization" as messagingOrganization <<MedComCoreOrganization>>
class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCorePractitionerRole" as pracRole
class "MedComCoreCareTeam" as careteam
class "MedComCorePractitioner" as author


message -- messageheader : "entry"
messageheader -- communication : "focus"
communication -- patient : "subject"
communication -- pracRole : "author role"
message -- provenance : "entry"
provenance -- messageheader : "target" 
provenance -- messagingOrganization : "agent.who"
communication -- careteam : "sender"
communication -- careteam : "recipient"
communication -- pracRole : "sender"
communication -- pracRole : "recipient"
pracRole -- author : "practitioner"


messageheader -- messagingOrganization : "receiver"
messageheader -- messagingOrganization : "sender"
@enduml