@startuml CareCommunicationCommunication

hide empty members

class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCorePractitioner" as author
class "Sender or recipient" as senderRec
class "MedComCareCommunicationMessageHeader" as messageheader <<MedComMessagingMessageHeader>>

messageheader -- communication : "focus"
communication -- patient : "subject"
communication -- author : "payload author"
communication -- senderRec : "sender/recipient"


messageheader -- messagingOrganization : "receiver"
messageheader -- messagingOrganization : "sender"
@enduml