on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  qa-report-status:
    uses: medcomdk/fhir-publishing/.github/workflows/qa-report.yaml@main